### ISSUE TITLE
Implement auto_contrast

### ISSUE THREAD

**Issue by larmarange** [larmarange/ggstats#75]
cf. https://github.com/teunbrand/ggplot_tricks?tab=readme-ov-file#text-contrast

**Comment by thombet** [comment]
Hello @larmarange, thanks for the great package that I've been using extensively 😃 

I comment here because it is not really an "issue" but rather a question related to this issue. If you prefer I open a new issue though, please let me know.

There is at least one case when I don't want to use the auto_contrast feature: when using a dodge bar plot with manual vertical alignment to move the label above the bar. Indeed, in this case, the color of the text contrasts with the background color of the bar, and not the background color of the bar anymore, resulting in poor readability.

Here is a screenshot as as example using the brewer palette `Dark2` (I may provide a reprex if needed):
![Image](https://github.com/user-attachments/assets/d59462d6-e0e1-4194-ad84-6a205f46b14b)

To disable the auto_contrast feature in this case, I provide `mapping = aes()` to the `geom_prop_text()` call but since I am not a R expert, I am wondering : is there a better solution?

Thank you in advance.

**Comment by thombet** [comment]
C'est parfait, merci pour la réponse rapide.

Une suggestion en passant : ne serait-il pas possible que la fonction auto_contrast détermine la couleur du texte en fonction de sa position finale ? (c'est-à-dire pas systématiquement en fonction de la couleur de la barre associée, mais en fonction de la couleur de l'arrière plan si le texte est décalé comme dans mon exemple)

**Comment by larmarange** [comment]
Malheureusement je ne vois pas comment implanter cela, car il faudrait pouvoir récupérer la couleur du fond en fonction de la position, ce qui n'est pas possible sans analyse du rendu final.

**Comment by thombet** [comment]
Je comprends. Merci d'avoir regardé comment faire 👍
